robot_name: 'go2' # 'anymal_d'

joint_names: &jn ["FL_hip_joint", "FL_thigh_joint", "FL_calf_joint", "FR_hip_joint", "FR_thigh_joint", "FR_calf_joint", "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint", "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint"]

base_name: "base"

state_topic: "go2/state" # "anymal_d/state"
command_topic: "go2/command" # "anymal_d/command"
change_controller_topic: "go2/change_controller" # "anymal_d/change_controller"
contact_topics: ["/lf_foot_contact", "/rf_foot_contact", "/lh_foot_contact","/rh_foot_contact"] 


state_publisher:
  update_rate: 400 # Hz

static_controller:
  stand_controller:
    joint_angles: [0.0, 0.4, -0.8, 0.0, -0.4, 0.8, 0.0, 0.4, -0.8, 0.0, -0.4, 0.8] # LF, LH, RF, RH
  sit_controller:
    joint_angles: [0.0, 1.5, -2.6, 0.0, -1.5, 2.6, 0.0, 1.5, -2.6, 0.0, -1.5, 2.6] # LF, LH, RF, RH
  kp: 400
  kd: 5
  interpolation_time: 1.0 # s
  rate: 50 # Hz

mpc_controller:
  wbc_type: "sqp"
  reference_trajectory:
    terrain_topic: "/convex_plane_decomposition_ros/filtered_map"
    reference_topic: "/go2_mpc_target" # "/anymal_mpc_target"
    observation_topic: "/go2_mpc_observation" # "/anymal_mpc_observation"
    traj_dt: 0.1
    traj_knots: 10
    blind: false

anymal_d:
  joint_controller:
      type: tbai_gazebo/JointController
      joints: *jn

reference_generator:
  type: "twist"

  joystick:
    topic: "joy"
    ramped_velocity: 5.0
    x_index: 1
    y_index: 0
    yaw_index: 3
    x_scale: 1.0
    y_scale: 0.5
    yaw_scale: 0.5

  twist:
    topic: "cmd_vel"

contact_sensor:
  update_rate: 20 # Hz